// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/generate_stellar_activation_xdr.dart from the pinned subset.

abstract final class StellarXdrConstants {
  static const int protocolVersion = 27;
  static const String xdrRelease = 'v27.0';
  static const String xdrCommit = '68fa1ac55692f68ad2a2ca549d0a283273554439';

  static const int keyTypeEd25519 = 0;
  static const int assetNative = 0;
  static const int assetAlphaNum4 = 1;
  static const int assetAlphaNum12 = 2;
  static const int operationCreateAccount = 0;
  static const int operationPayment = 1;
  static const int operationChangeTrust = 6;
  static const int preconditionNone = 0;
  static const int preconditionTime = 1;
  static const int memoNone = 0;
  static const int envelopeTypeTransaction = 2;
  static const int extensionV0 = 0;
  static const int maxOperations = 100;
  static const int maxSignatures = 20;
  static const int maxSignatureBytes = 64;
}
