import 'dart:convert';
import 'dart:io';

void main() {
  final Map<String, dynamic> schema =
      jsonDecode(
            File('tool/stellar_activation_xdr_subset.json').readAsStringSync(),
          )
          as Map<String, dynamic>;
  final Map<String, dynamic> constants =
      schema['constants']! as Map<String, dynamic>;
  final StringBuffer output = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln(
      '// Generated by tool/generate_stellar_activation_xdr.dart from the pinned subset.',
    )
    ..writeln()
    ..writeln('abstract final class StellarXdrConstants {')
    ..writeln(
      '  static const int protocolVersion = ${schema['protocolVersion']};',
    )
    ..writeln("  static const String xdrRelease = '${schema['xdrRelease']}';")
    ..writeln("  static const String xdrCommit = '${schema['xdrCommit']}';")
    ..writeln();
  for (final MapEntry<String, dynamic> entry in constants.entries) {
    output.writeln('  static const int ${entry.key} = ${entry.value};');
  }
  output.writeln('}');
  File(
    'lib/wallet_sdk/src/protocol/xdr/stellar_xdr_constants.g.dart',
  ).writeAsStringSync(output.toString());
}
